apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-grpc-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sum-grpc
  template:
    metadata:
      labels:
        app: sum-grpc
    spec:
      containers:
        - name: sum-grpc-app
          image: georgemaged/sum-app-grpc:latest
          ports:
            - containerPort: 50051

